# Generated by Django 4.2.4 on 2023-09-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientportion',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='shoppinglistingredientportion',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='supplementaryingredientportion',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
