# Generated by Django 4.2.4 on 2023-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_recipeingredientportion_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
