# Generated by Django 4.2.4 on 2023-09-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fatsecret_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
