# Generated by Django 4.2.4 on 2023-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_ingredient_fatsecret_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fatsecret_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
