# Generated by Django 4.2.4 on 2023-09-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_ingredient_fatsecret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fatsecret_json',
            field=models.TextField(blank=True),
        ),
    ]
