# Generated by Django 4.2.4 on 2023-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_ingredient_calories_ingredient_fatsecret_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionday',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
